name: deep_ie_3d
description: Web application displaying the capabilities of DeepIE3D
version: 1.0.0
author: Adrian Westh <mail@adrianwesth.dk> & Simon Krabbe Munck <simonkmunck@gmail.com>

environment:
  sdk: '>=2.6.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  js: ^0.6.1+1
  tuple: ^1.0.3

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  pedantic: ^1.8.0+1